In [1]:
import pandas as pd

In [2]:
data={"House" : ["H1","H2","H3","H4","H5"],
    "Area":[800,1000,1200,1500,2000],
    
   }

In [3]:
df=pd.DataFrame(data)
df

  House  Area
0    H1   800
1    H2  1000
2    H3  1200
3    H4  1500
4    H5  2000

In [4]:
x=df.iloc[:,[1]]

In [5]:
x

   Area
0   800
1  1000
2  1200
3  1500
4  2000

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
scaler=MinMaxScaler()

In [8]:
scaler.fit_transform(x)

array([[0.        ],
       [0.16666667],
       [0.33333333],
       [0.58333333],
       [1.        ]])

In [10]:
predication=scaler.fit([[1300]])

ValueError: Expected 2D array, got 1D array instead:
array=[1300.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.