In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

In [3]:
df=pd.read_csv(r"C:\Users\khush\Downloads\placement.csv (For Simple Linear Regression)")

In [4]:
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [5]:
x=df[["cgpa"]]
x

     cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [6]:
y=df[["package"]]
y

     package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [7]:
# pl.title("GGPA VS PACKAGE")
# pl.xlabel("CGPA")
# pl.xlabel("PACKGE")
# pl.scatter(x,y)

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=2)

In [10]:
x_train

     cgpa
137  7.14
163  8.93
111  5.42
123  5.10
109  7.77
..    ...
43   7.66
22   6.14
72   7.78
15   7.25
168  8.65

[160 rows x 1 columns]

In [11]:
x_test

     cgpa
112  8.58
29   7.15
182  5.88
199  6.22
193  4.57
85   4.79
10   5.32
54   6.86
115  8.35
35   6.87
12   8.94
92   7.90
13   6.93
126  5.91
174  7.32
2    7.82
44   5.09
3    7.42
113  6.94
14   7.73
23   6.19
25   7.28
6    6.73
134  7.20
165  8.21
173  6.75
45   7.87
65   7.60
48   8.63
122  5.12
178  8.15
64   7.36
9    8.31
57   6.60
78   6.59
71   7.47
128  7.93
176  6.29
131  6.37
53   6.47

In [12]:
y_train

     package
137     3.13
163     3.91
111     2.25
123     2.30
109     4.06
..       ...
43      2.76
22      2.30
72      3.62
15      3.23
168     3.52

[160 rows x 1 columns]

In [13]:
y_test

     package
112     4.10
29      3.49
182     2.08
199     2.33
193     1.94
85      1.48
10      1.86
54      3.09
115     4.21
35      2.87
12      3.65
92      4.00
13      2.89
126     2.60
174     2.99
2       3.25
44      1.86
3       3.67
113     2.37
14      3.42
23      2.48
25      3.65
6       2.60
134     2.83
165     4.08
173     2.56
45      3.58
65      3.81
48      4.09
122     2.01
178     3.63
64      2.92
9       3.51
57      1.94
78      2.21
71      3.34
128     3.34
176     3.23
131     2.01
53      2.61

In [14]:

from sklearn.linear_model import LinearRegression

In [15]:
lr=LinearRegression()

In [16]:
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
pre=lr.predict(x_test)

In [18]:


pre

array([[3.89111601],
       [3.09324469],
       [2.38464568],
       [2.57434935],
       [1.6537286 ],
       [1.77647803],
       [2.07219258],
       [2.93143862],
       [3.76278706],
       [2.93701814],
       [4.09197872],
       [3.51170867],
       [2.97049525],
       [2.40138424],
       [3.18809652],
       [3.46707251],
       [1.94386362],
       [3.24389172],
       [2.97607477],
       [3.41685683],
       [2.55761079],
       [3.16577844],
       [2.85890486],
       [3.12114229],
       [3.68467378],
       [2.8700639 ],
       [3.49497011],
       [3.34432308],
       [3.91901361],
       [1.96060218],
       [3.65119666],
       [3.2104146 ],
       [3.74046898],
       [2.7863711 ],
       [2.78079158],
       [3.27178932],
       [3.52844723],
       [2.61340599],
       [2.65804215],
       [2.71383735]])

In [19]:
#y=mx+b

In [20]:
m=lr.coef_
m

array([[0.55795197]])

In [21]:
b=lr.intercept_
b

array([-0.89611192])

In [22]:
y=m*(8.58)+b

In [23]:
y

array([[3.89111601]])

In [24]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error,r2_score

In [25]:
print("MAE:",mean_absolute_error(y_test,pre))

MAE: 0.2884710931878175

In [26]:
print("MSE",mean_squared_error(y_test,pre))

MSE 0.12129235313495527

In [27]:
print("RMSE:",root_mean_squared_error(y_test,pre))

RMSE: 0.34827051717731616

In [28]:
print("R2Score:",r2_score(y_test,pre))
r2=r2_score(y_test,pre)
r2

R2Score: 0.780730147510384

0.780730147510384

In [29]:
#Acjection R2Score
#ajc_r2=1-(1-r2)*(n-1)/(n-1-k)
len(y_test)

40

In [30]:
ajc_r2=(1-r2)*(40-1)/(40-1-1)
ajc_r2

0.2250401117656585

In [32]:
# import matplotlib.pyplot as pl  # Assuming you imported it as pl

# pl.title("CGPA VS PACKAGE")
# pl.xlabel("CGPA")
# pl.ylabel("PACKAGE")          # Fixed: Changed from xlabel to ylabel

# pl.scatter(x, y)
# pl.plot(x, pre, color="red")  # This is correct, provided 'pre' holds your predictions
# pl.show()