In [3]:
import pandas as pd

In [7]:
data={"House" : ["H1","H2","H3","H4","H5"],
    "Area":[800,1000,1200,1500,2000],
    
   }

In [8]:
df=pd.DataFrame(data)

In [9]:
df

  House  Area
0    H1   800
1    H2  1000
2    H3  1200
3    H4  1500
4    H5  2000

In [10]:
x=df.iloc[:,[1]]

In [11]:
x

   Area
0   800
1  1000
2  1200
3  1500
4  2000

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler=StandardScaler()

In [14]:
scaler.fit_transform(x)

array([[-1.19182824],
       [-0.71509694],
       [-0.23836565],
       [ 0.47673129],
       [ 1.66855953]])

In [17]:
Predication=scaler.transform([[1300]])
Predication

array([[0.]])